/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Logic.BasicCalculator;

import Logic.JFMainPantalla;

/**
 *
 * @author TheOneAboveAll
 */
public class JFBasicCalculator extends javax.swing.JFrame {

    private Double total;
    private Double num1;
    private Double num2;
    private int operacion;
    private int base = 2;
    private boolean permiso;
    public int pp;
    /**
     * Creates new form JFBasicCalculator
     */
    public JFBasicCalculator() {
        initComponents();
        
    }
    
    //Metodos GETTERS y SETTERS
    public void setTotal(Double t){     this.total = t;     }  
    public void setNum1(Double n){     this.num1 = n;    }
    public void setNum2(Double n){     this.num2 = n;    }
    public void setOperacion(int op){       this.operacion = op;    }
    public void setBase(int b){     this.base = b;      }
    
    
    
    public Double getTotal(){       return this.total;}
    public Double getNum1(){     return this.num1;        }
    public Double getNum2(){     return this.num2;        }
    public int getOperacion(){       return this.operacion;}
    public int getBase(){      return this.base;}
    
    
    private void operaciones(int op, int base){
        
        switch(op){       
            case 0: //suma
                if(this.getTotal() == null){    this.setTotal(0.0);     }
                //se traen los valores actuales de ambos numeros que esten guardados y se suman, ademas de colocar el resultado en la 
                this.setTotal(this.getTotal() + this.getNum1() + this.getNum2());  System.out.println("el num 1 " + this.getNum1());  
               break;
            case 1: //resta
                if(this.getTotal() == null){   
                           this.setTotal(this.getNum1() - this.getNum2());  
                           //
                } else if (this.getTotal() != null){       this.setTotal(this.getTotal() - this.getNum1() - this.getNum2());  }
               
                break;
            case 2: //multiplicacion
                 if(this.getTotal() == null){   this.setTotal(1.0); } 
                 
                 this.setTotal(this.getTotal() * this.getNum1() * this.getNum2()); 
                break;
            case 3: //division
                
                break;
            case 4:  //porcentaje
                
                break;
            case 5: //raiz
                
                break;
            case 6:  //potencia
                
                break;
            case 7: System.out.println("caso  7"); this.setTotal(this.getNum1());
            
            default:    System.out.println("Error en la seleccion de operaciones"); break;
        }
     this.jLResultado.setText(this.getTotal() + ""); //se va a colocar el resultado previamente guardado
    
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jBDivicion = new javax.swing.JButton();
        jBResta = new javax.swing.JButton();
        jBMultiplicacion = new javax.swing.JButton();
        jBSuma = new javax.swing.JButton();
        jBRaiz = new javax.swing.JButton();
        jBPotencia = new javax.swing.JButton();
        jBUltimoResultado = new javax.swing.JButton();
        jBBorrarUltimoNumero = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLResultado = new javax.swing.JLabel();
        jLOperaciones = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jBBorrarTodo = new javax.swing.JButton();
        jBPorcentaje = new javax.swing.JButton();
        jBIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(22, 22, 22));
        jLabel2.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("    Calculadora Básica");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 280, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/imgBasicCalculator.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 310));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 80, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 80, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 80, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 80, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 80, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("00");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 80, -1));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setText("8");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 80, -1));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("9");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 80, -1));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText("7");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 80, -1));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("0");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 80, -1));

        jBDivicion.setBackground(new java.awt.Color(255, 255, 255));
        jBDivicion.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBDivicion.setForeground(new java.awt.Color(0, 0, 0));
        jBDivicion.setText("÷");
        jPanel1.add(jBDivicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 80, -1));

        jBResta.setBackground(new java.awt.Color(255, 255, 255));
        jBResta.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBResta.setForeground(new java.awt.Color(0, 0, 0));
        jBResta.setText("-");
        jBResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestaActionPerformed(evt);
            }
        });
        jPanel1.add(jBResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 80, -1));

        jBMultiplicacion.setBackground(new java.awt.Color(255, 255, 255));
        jBMultiplicacion.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBMultiplicacion.setForeground(new java.awt.Color(0, 0, 0));
        jBMultiplicacion.setText("x");
        jBMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(jBMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 80, -1));

        jBSuma.setBackground(new java.awt.Color(255, 255, 255));
        jBSuma.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBSuma.setForeground(new java.awt.Color(0, 0, 0));
        jBSuma.setText("+");
        jBSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSumaActionPerformed(evt);
            }
        });
        jPanel1.add(jBSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 80, -1));

        jBRaiz.setBackground(new java.awt.Color(255, 255, 255));
        jBRaiz.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBRaiz.setForeground(new java.awt.Color(0, 0, 0));
        jBRaiz.setText("√");
        jPanel1.add(jBRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 80, -1));

        jBPotencia.setBackground(new java.awt.Color(255, 255, 255));
        jBPotencia.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBPotencia.setForeground(new java.awt.Color(0, 0, 0));
        jBPotencia.setText("^");
        jPanel1.add(jBPotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 80, -1));

        jBUltimoResultado.setBackground(new java.awt.Color(255, 255, 255));
        jBUltimoResultado.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBUltimoResultado.setForeground(new java.awt.Color(0, 0, 0));
        jBUltimoResultado.setText("ANS");
        jBUltimoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUltimoResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(jBUltimoResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 80, -1));

        jBBorrarUltimoNumero.setBackground(new java.awt.Color(255, 255, 255));
        jBBorrarUltimoNumero.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBBorrarUltimoNumero.setForeground(new java.awt.Color(0, 0, 0));
        jBBorrarUltimoNumero.setText("Borrar último");
        jBBorrarUltimoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarUltimoNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jBBorrarUltimoNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, -1));

        jTextField1.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("2");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 130, -1));

        jLabel3.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Resultado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jLResultado.setBackground(new java.awt.Color(102, 102, 102));
        jLResultado.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jLResultado.setForeground(new java.awt.Color(255, 255, 255));
        jLResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLResultado.setText("0.00");
        jLResultado.setOpaque(true);
        jPanel1.add(jLResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 330, 40));

        jLOperaciones.setBackground(new java.awt.Color(102, 102, 102));
        jLOperaciones.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jLOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLOperaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLOperaciones.setOpaque(true);
        jPanel1.add(jLOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 280, 40));

        jLabel6.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Base de √ ó ^:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 150, -1, -1));

        jLabel7.setBackground(new java.awt.Color(22, 22, 22));
        jLabel7.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Regresar al menú principal");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 190, 30));

        jLabel8.setBackground(new java.awt.Color(22, 22, 22));
        jLabel8.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Exit");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 70, 30));

        jButton21.setBackground(new java.awt.Color(255, 255, 255));
        jButton21.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 0, 0));
        jButton21.setText("π");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 80, -1));

        jBBorrarTodo.setBackground(new java.awt.Color(255, 255, 255));
        jBBorrarTodo.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBBorrarTodo.setForeground(new java.awt.Color(0, 0, 0));
        jBBorrarTodo.setText("Borrar todo");
        jBBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(jBBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 170, -1));

        jBPorcentaje.setBackground(new java.awt.Color(255, 255, 255));
        jBPorcentaje.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBPorcentaje.setForeground(new java.awt.Color(0, 0, 0));
        jBPorcentaje.setText("%");
        jPanel1.add(jBPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 80, -1));

        jBIgual.setBackground(new java.awt.Color(255, 255, 255));
        jBIgual.setFont(new java.awt.Font("Hack Nerd Font Mono", 0, 15)); // NOI18N
        jBIgual.setForeground(new java.awt.Color(0, 0, 0));
        jBIgual.setText("=");
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });
        jPanel1.add(jBIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         System.exit(0); //Sales de todo el sistema
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
         JFMainPantalla  mainPantalla = new JFMainPantalla();   mainPantalla.setVisible(true); //creamos el objeto pantalla main y la hacemos visible
         mainPantalla.setLocationRelativeTo(null);  //coloca la ventana emergente exactamente en el centro de la pantalla
        this.dispose(); //se cirran todas las ventanas actualles
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jBBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarTodoActionPerformed
        this.jLOperaciones.setText(""); //se borra cualquier numero que haya estado 
        this.jLResultado.setText("0.00");   this.setTotal(null); this.setNum1(null); this.setNum2(null);
    }//GEN-LAST:event_jBBorrarTodoActionPerformed

    private void jBBorrarUltimoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarUltimoNumeroActionPerformed
       this.jLOperaciones.setText("");  //se borra el numero que se haya escrito en pantalla
    }//GEN-LAST:event_jBBorrarUltimoNumeroActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLOperaciones.setText(jLOperaciones.getText() + "1"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 1
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "2"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 2
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "3"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 3
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLOperaciones.setText(jLOperaciones.getText() + "4"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 4
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "5"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 5
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jLOperaciones.setText(jLOperaciones.getText() + "6"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 6
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "7"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 7
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "8"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 8
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "9"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 9
       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
         jLOperaciones.setText(jLOperaciones.getText() + "0"); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 0
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         this.jLOperaciones.setText(jLOperaciones.getText() + "00");    
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar 00
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
         this.jLOperaciones.setText("" + Math.PI); 
        //Se coloca el texto, pero previamente se obtiene el texto que este en el recuadro y se le va a concatenar PI
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jBSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSumaActionPerformed
        this.multi_Y_Divicion(Double.valueOf(jLOperaciones.getText()));
        
        this.setOperacion(0);
       
           
          if((this.getNum2() == null ) && ( this.getNum1() != null)){
                   this.setNum2(Double.valueOf(this.jLOperaciones.getText()));
                   this.jLOperaciones.setText("");  //limpiamos la pantalla de operaciones
                   
                   this.operaciones((int) this.getOperacion(), (int) this.getBase());  //
                   
                    this.setNum1(null); this.setNum2(null);//reiniciamos ambas varaibles por si acaso
                   
         } else if((this.getNum1() == null ) && this.getNum2() == null){
                  this.setNum1(Double.valueOf(this.jLOperaciones.getText()));
                  this.jLOperaciones.setText("");   //limpiamos la pantalla de operaciones
                  
         }  
    }//GEN-LAST:event_jBSumaActionPerformed

    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed
       
       if(this.getNum1() != null){
            this.setNum2(Double.valueOf(this.jLOperaciones.getText()));
            
       
       } 
         this.operaciones((int) this.getOperacion(), (int) this.getBase());    
      
       //reiniciamos ambas varaibles por si acaso
      
       this.setNum2(null); this.setNum2(null);
       this.jLOperaciones.setText(""); 
       this.jLResultado.setText(this.getTotal() + "");
       
    }//GEN-LAST:event_jBIgualActionPerformed

    private void jBRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRestaActionPerformed
        this.multi_Y_Divicion(Double.valueOf(jLOperaciones.getText()));
        this.setOperacion(1);
           
          if((this.getNum2() == null) && (this.getNum1() != null)){
                   this.setNum2(Double.valueOf(this.jLOperaciones.getText()));
                  
                   System.out.println("se hace  la resta");
                   this.operaciones((int) this.getOperacion(), (int) this.getBase());  
                    this.setNum1(null); this.setNum2(null);//reiniciamos ambas varaibles por si acaso
                     this.jLOperaciones.setText("");  //limpiamos la pantalla de operaciones
                   
         } else if((this.getNum1() == null) && (this.getNum2() == null)){
                  this.setNum1(Double.valueOf(this.jLOperaciones.getText()));
                  this.jLOperaciones.setText("");   //limpiamos la pantalla de operaciones
                  
         }  
    }//GEN-LAST:event_jBRestaActionPerformed

    private void jBUltimoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUltimoResultadoActionPerformed
       jLOperaciones.setText(jLResultado.getText());    //pasamos el numero del recuadro de resultado y lo ponemos en el reuadro de operaciones
       jLResultado.setText("0.00"); //colocamos 0 en el cuadro del resultado
       this.setNum1(null); this.setNum2(null); this.setTotal(null);
    }//GEN-LAST:event_jBUltimoResultadoActionPerformed

    private void jBMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicacionActionPerformed
         this.setOperacion(2);
         
           
          if(this.getNum2() == null && !(this.getNum1() == null)){
                   this.setNum2(Double.valueOf(this.jLOperaciones.getText()));
                   this.jLOperaciones.setText("");  //limpiamos la pantalla de operaciones
                   
                   this.operaciones((int) this.getOperacion(), (int) this.getBase());  
                    this.setNum1(null); this.setNum2(null);//reiniciamos ambas varaibles por si acaso
                   
         } else if((this.getNum1() == null ) && this.getNum2() == null){
                  this.setNum1(Double.valueOf(this.jLOperaciones.getText()));
                  this.jLOperaciones.setText("");   //limpiamos la pantalla de operaciones
                  
         }  
        
          
    }//GEN-LAST:event_jBMultiplicacionActionPerformed

     public void multi_Y_Divicion(Double num2){
        if((this.getNum1() != null)  && (this.getNum2() == null) && (this.getOperacion() == 2)){
                this.setOperacion(7);
                num2 *= this.getNum1();
                this.setNum1(num2);
                //this.jLOperaciones.setText(this.getNum1() + "");
                this.jLResultado.setText(this.getNum1() + "");  System.out.println("numero colocado");
                
        } else if( (this.getNum1() != null)  && (this.getNum2() == null) && this.getOperacion() == 3 ){
           
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFBasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFBasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFBasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFBasicCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFBasicCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBorrarTodo;
    private javax.swing.JButton jBBorrarUltimoNumero;
    private javax.swing.JButton jBDivicion;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBMultiplicacion;
    private javax.swing.JButton jBPorcentaje;
    private javax.swing.JButton jBPotencia;
    private javax.swing.JButton jBRaiz;
    private javax.swing.JButton jBResta;
    private javax.swing.JButton jBSuma;
    private javax.swing.JButton jBUltimoResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLOperaciones;
    private javax.swing.JLabel jLResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
