/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sitemacosteoporordenes.Prosesos;

import sitemacosteoporordenes.VentaPrincipal;

/**
 *
 * @author monfi
 */
public class VRequisicionDeMateriales extends javax.swing.JFrame {

    /**
     * Creates new form VRequisicionDeMateriales
     */
    public VRequisicionDeMateriales() {
        initComponents();
    }
     public static String numeroOrden="";
    public static String fecha="";
    
    public static String d1 = "";
    public static String d2 = "";
    public static String d3 = "";
    public static String d4 = "";
    public static String d5 = "";
    
    public static double ct1 = 0;
    public static double ct2 = 0;
    public static double ct3 = 0;
    public static double ct4 = 0;
    public static double ct5 = 0;
    
    public static double td = 0;
    public static double ti = 0;
    
    public static double tm = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTNumeroRequisicion = new javax.swing.JTextField();
        jTDepartamento = new javax.swing.JTextField();
        jTNumeroOrden = new javax.swing.JTextField();
        jTFecha = new javax.swing.JTextField();
        jTDescripcion1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTCantidad = new javax.swing.JTextField();
        jTCantidad2 = new javax.swing.JTextField();
        jTCantidad3 = new javax.swing.JTextField();
        jTCantidad4 = new javax.swing.JTextField();
        jTDescripcion2 = new javax.swing.JTextField();
        jTDescripcion3 = new javax.swing.JTextField();
        jTDescripcion4 = new javax.swing.JTextField();
        jRTipoMaterial1 = new javax.swing.JRadioButton();
        jRTipoMaterial2 = new javax.swing.JRadioButton();
        jRTipoMaterial3 = new javax.swing.JRadioButton();
        jRTipoMaterial4 = new javax.swing.JRadioButton();
        jRTipoMaterial5 = new javax.swing.JRadioButton();
        jRTipoMaterial6 = new javax.swing.JRadioButton();
        jRTipoMaterial7 = new javax.swing.JRadioButton();
        jRTipoMaterial8 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jTCostoUnitario = new javax.swing.JTextField();
        jTCostoUnitario2 = new javax.swing.JTextField();
        jTCostoUnitario3 = new javax.swing.JTextField();
        jTCostoUnitario4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTTotalDirecto = new javax.swing.JTextField();
        jTTotalIndirecto = new javax.swing.JTextField();
        jTTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 245, 225));
        jPanel1.setForeground(new java.awt.Color(30, 30, 30));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setText("Requisicion de Materiales  ");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Numero de requisicion:");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(30, 30, 30));
        jLabel3.setText("Departamento:");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Numero de Orden:");

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(30, 30, 30));
        jLabel5.setText("Fecha:");

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(30, 30, 30));
        jLabel6.setText("Cantidad");

        jTNumeroRequisicion.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroRequisicion.setForeground(new java.awt.Color(30, 30, 30));
        jTNumeroRequisicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumeroRequisicionActionPerformed(evt);
            }
        });

        jTDepartamento.setBackground(new java.awt.Color(255, 255, 255));
        jTDepartamento.setForeground(new java.awt.Color(30, 30, 30));
        jTDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDepartamentoActionPerformed(evt);
            }
        });

        jTNumeroOrden.setBackground(new java.awt.Color(255, 255, 255));
        jTNumeroOrden.setForeground(new java.awt.Color(30, 30, 30));

        jTFecha.setBackground(new java.awt.Color(255, 255, 255));
        jTFecha.setForeground(new java.awt.Color(30, 30, 30));
        jTFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFechaActionPerformed(evt);
            }
        });

        jTDescripcion1.setBackground(new java.awt.Color(255, 255, 255));
        jTDescripcion1.setForeground(new java.awt.Color(30, 30, 30));
        jTDescripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescripcion1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Descripcion");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Tipo de material");

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Costo Unitario");

        jTCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTCantidad.setForeground(new java.awt.Color(30, 30, 30));
        jTCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantidadActionPerformed(evt);
            }
        });

        jTCantidad2.setBackground(new java.awt.Color(255, 255, 255));
        jTCantidad2.setForeground(new java.awt.Color(30, 30, 30));
        jTCantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantidad2ActionPerformed(evt);
            }
        });

        jTCantidad3.setBackground(new java.awt.Color(255, 255, 255));
        jTCantidad3.setForeground(new java.awt.Color(30, 30, 30));
        jTCantidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantidad3ActionPerformed(evt);
            }
        });

        jTCantidad4.setBackground(new java.awt.Color(255, 255, 255));
        jTCantidad4.setForeground(new java.awt.Color(30, 30, 30));
        jTCantidad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantidad4ActionPerformed(evt);
            }
        });

        jTDescripcion2.setBackground(new java.awt.Color(255, 255, 255));
        jTDescripcion2.setForeground(new java.awt.Color(30, 30, 30));
        jTDescripcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescripcion2ActionPerformed(evt);
            }
        });

        jTDescripcion3.setBackground(new java.awt.Color(255, 255, 255));
        jTDescripcion3.setForeground(new java.awt.Color(30, 30, 30));
        jTDescripcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescripcion3ActionPerformed(evt);
            }
        });

        jTDescripcion4.setBackground(new java.awt.Color(255, 255, 255));
        jTDescripcion4.setForeground(new java.awt.Color(30, 30, 30));
        jTDescripcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDescripcion4ActionPerformed(evt);
            }
        });

        jRTipoMaterial1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial1.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial1.setText("Directo");
        jRTipoMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial1ActionPerformed(evt);
            }
        });

        jRTipoMaterial2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial2.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial2.setText("Directo");
        jRTipoMaterial2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial2ActionPerformed(evt);
            }
        });

        jRTipoMaterial3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial3.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial3.setText("Directo");
        jRTipoMaterial3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial3ActionPerformed(evt);
            }
        });

        jRTipoMaterial4.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial4.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial4.setText("Directo");
        jRTipoMaterial4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial4ActionPerformed(evt);
            }
        });

        jRTipoMaterial5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial5.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial5.setText("Indirecto");
        jRTipoMaterial5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial5ActionPerformed(evt);
            }
        });

        jRTipoMaterial6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial6.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial6.setText("Indirecto");
        jRTipoMaterial6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial6ActionPerformed(evt);
            }
        });

        jRTipoMaterial7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial7.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial7.setText("Indirecto");
        jRTipoMaterial7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTipoMaterial7ActionPerformed(evt);
            }
        });

        jRTipoMaterial8.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jRTipoMaterial8.setForeground(new java.awt.Color(30, 30, 30));
        jRTipoMaterial8.setText("Indirecto");

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(30, 30, 30));
        jLabel10.setText("Costo Total");

        jTCostoUnitario.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoUnitario.setForeground(new java.awt.Color(30, 30, 30));
        jTCostoUnitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoUnitarioActionPerformed(evt);
            }
        });

        jTCostoUnitario2.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoUnitario2.setForeground(new java.awt.Color(30, 30, 30));

        jTCostoUnitario3.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoUnitario3.setForeground(new java.awt.Color(30, 30, 30));
        jTCostoUnitario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoUnitario3ActionPerformed(evt);
            }
        });

        jTCostoUnitario4.setBackground(new java.awt.Color(255, 255, 255));
        jTCostoUnitario4.setForeground(new java.awt.Color(30, 30, 30));

        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("0.0");

        jLabel12.setForeground(new java.awt.Color(30, 30, 30));
        jLabel12.setText("0.0");

        jLabel13.setForeground(new java.awt.Color(30, 30, 30));
        jLabel13.setText("0.0");

        jLabel14.setForeground(new java.awt.Color(30, 30, 30));
        jLabel14.setText("0.0");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jBVolver.setBackground(new java.awt.Color(139, 69, 19));
        jBVolver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(255, 255, 255));
        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jBGuardar.setBackground(new java.awt.Color(234, 178, 102));
        jBGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(195, 127, 61));
        jButton5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Volver");

        jLabel15.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 30, 30));
        jLabel15.setText("Total Indirecto");

        jLabel16.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 30, 30));
        jLabel16.setText("Total directo");

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 30, 30));
        jLabel17.setText("Total");

        jTTotalDirecto.setBackground(new java.awt.Color(255, 255, 255));
        jTTotalDirecto.setForeground(new java.awt.Color(30, 30, 30));
        jTTotalDirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotalDirectoActionPerformed(evt);
            }
        });

        jTTotalIndirecto.setBackground(new java.awt.Color(255, 255, 255));
        jTTotalIndirecto.setForeground(new java.awt.Color(30, 30, 30));
        jTTotalIndirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTTotalIndirectoActionPerformed(evt);
            }
        });

        jTTotal.setBackground(new java.awt.Color(255, 255, 255));
        jTTotal.setForeground(new java.awt.Color(30, 30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRTipoMaterial2)
                                                            .addComponent(jRTipoMaterial3)
                                                            .addComponent(jRTipoMaterial4))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jRTipoMaterial6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTCostoUnitario2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jRTipoMaterial8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTCostoUnitario4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jRTipoMaterial7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTCostoUnitario3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jRTipoMaterial1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jRTipoMaterial5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel9)
                                                            .addComponent(jTCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(255, 255, 255)
                                        .addComponent(jLabel8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTNumeroRequisicion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTTotalIndirecto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTTotalDirecto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25)
                                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))))
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jBVolver)
                .addGap(46, 46, 46)
                .addComponent(jBGuardar)
                .addGap(56, 56, 56)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTNumeroRequisicion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jTTotalDirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTNumeroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel15)
                            .addComponent(jTTotalIndirecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTDescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRTipoMaterial1)
                                    .addComponent(jRTipoMaterial5)
                                    .addComponent(jTCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTDescripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRTipoMaterial2)
                                    .addComponent(jRTipoMaterial6)
                                    .addComponent(jTCostoUnitario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTCantidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTDescripcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRTipoMaterial3)
                                    .addComponent(jRTipoMaterial7)
                                    .addComponent(jLabel13)
                                    .addComponent(jTCostoUnitario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRTipoMaterial4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTCantidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTDescripcion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRTipoMaterial8)
                                        .addComponent(jTCostoUnitario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))))
                            .addComponent(jLabel12))
                        .addGap(34, 82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jBVolver)
                            .addComponent(jBGuardar))
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDepartamentoActionPerformed

    private void jTFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFechaActionPerformed

    private void jTNumeroRequisicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumeroRequisicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroRequisicionActionPerformed

    private void jTDescripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescripcion1ActionPerformed

    private void jTCantidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantidad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantidad3ActionPerformed

    private void jRTipoMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial1ActionPerformed

    private void jRTipoMaterial2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial2ActionPerformed

    private void jRTipoMaterial5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial5ActionPerformed

    private void jRTipoMaterial7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial7ActionPerformed

    private void jTCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantidadActionPerformed

    private void jTCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantidad2ActionPerformed

    private void jTCantidad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantidad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantidad4ActionPerformed

    private void jRTipoMaterial3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial3ActionPerformed

    private void jRTipoMaterial4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial4ActionPerformed

    private void jTDescripcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescripcion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescripcion2ActionPerformed

    private void jTDescripcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescripcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescripcion4ActionPerformed

    private void jRTipoMaterial6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTipoMaterial6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTipoMaterial6ActionPerformed

    private void jTCostoUnitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoUnitarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoUnitarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTTotalDirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotalDirectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalDirectoActionPerformed

    private void jTTotalIndirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTTotalIndirectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTTotalIndirectoActionPerformed

    private void jTCostoUnitario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoUnitario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoUnitario3ActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
        
        VentaPrincipal ventana = new VentaPrincipal();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        
        //costos totales
        Double c1 = Double.parseDouble(jTextField5.getText());        
        Double c2 = Double.parseDouble(jTextField6.getText());
        Double c3 = Double.parseDouble(jTextField7.getText());
        Double c4 = Double.parseDouble(jTextField8.getText());
        Double c5 = Double.parseDouble(jTextField9.getText());
        
        
        d1 = jTextField10.getText();        
        d1 = jTextField11.getText();        
        d1 = jTextField12.getText();        
        d1 = jTextField12.getText();        
        d1 = jTextField14.getText();        
        //costos unitarios
        Double cu1 = Double.parseDouble(jTextField15.getText());
        Double cu2 = Double.parseDouble(jTextField16.getText());
        Double cu3 = Double.parseDouble(jTextField17.getText());
        Double cu4 = Double.parseDouble(jTextField18.getText());
        Double cu5 = Double.parseDouble(jTextField19.getText());
        
        ct1 = c1 * cu1;
        ct2 = c2 * cu2;
        ct3 = c3 * cu3;
        ct4 = c4 * cu4;
        ct5 = c5 * cu5;
        
        jLabel15.setText(String.valueOf(ct1));
        jLabel16.setText(String.valueOf(ct2));
        jLabel17.setText(String.valueOf(ct3));
        jLabel18.setText(String.valueOf(ct4));
        jLabel19.setText(String.valueOf(ct5));
        
        if (jRadioButton1.isSelected() ) {
          td=td+ct1;  
        }
        if(jRadioButton2.isSelected()){
            ti=ti+ct1;   
        }
        if (jRadioButton3.isSelected() ) {
          td=td+ct2;  
        }
        if(jRadioButton7.isSelected()){
            ti=ti+ct2;
        }
        if (jRadioButton4.isSelected() ) {
          td=td+ct3;  
        }
        if(jRadioButton8.isSelected()){
            ti=ti+ct3;  
        }
        if (jRadioButton5.isSelected() ) {
          td=td+ct4;  
        }
        if(jRadioButton9.isSelected()){
            ti=ti+ct4;  
        }
        if (jRadioButton6.isSelected() ) {
          td=td+ct5;  
        }
        if(jRadioButton10.isSelected()){
            ti=ti+ct5;
        }
        
        numeroOrden=txtNO.getText();
        fecha=jTextField2.getText();

        
        jLabel13.setText(String.valueOf(td));
        jLabel14.setText(String.valueOf(ti));
        
       tm=td+ti;
       
       jLabel22.setText(String.valueOf(tm));
        
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTDescripcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDescripcion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDescripcion3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRTipoMaterial1;
    private javax.swing.JRadioButton jRTipoMaterial2;
    private javax.swing.JRadioButton jRTipoMaterial3;
    private javax.swing.JRadioButton jRTipoMaterial4;
    private javax.swing.JRadioButton jRTipoMaterial5;
    private javax.swing.JRadioButton jRTipoMaterial6;
    private javax.swing.JRadioButton jRTipoMaterial7;
    private javax.swing.JRadioButton jRTipoMaterial8;
    private javax.swing.JTextField jTCantidad;
    private javax.swing.JTextField jTCantidad2;
    private javax.swing.JTextField jTCantidad3;
    private javax.swing.JTextField jTCantidad4;
    private javax.swing.JTextField jTCostoUnitario;
    private javax.swing.JTextField jTCostoUnitario2;
    private javax.swing.JTextField jTCostoUnitario3;
    private javax.swing.JTextField jTCostoUnitario4;
    private javax.swing.JTextField jTDepartamento;
    private javax.swing.JTextField jTDescripcion1;
    private javax.swing.JTextField jTDescripcion2;
    private javax.swing.JTextField jTDescripcion3;
    private javax.swing.JTextField jTDescripcion4;
    private javax.swing.JTextField jTFecha;
    private javax.swing.JTextField jTNumeroOrden;
    private javax.swing.JTextField jTNumeroRequisicion;
    private javax.swing.JTextField jTTotal;
    private javax.swing.JTextField jTTotalDirecto;
    private javax.swing.JTextField jTTotalIndirecto;
    // End of variables declaration//GEN-END:variables
}
